package enums;

public enum AuctionProperties {

     TOPIC, AUCTION_TYPE, AUCTION_SUBTYPE, DEVICE_NUM_FUNCTION, QUALITY_FUNCTION, DEVICE_NUM_RESTRICTION, QUALITY_RESTRICTION, HELPER_FLAG, STREAM_TIME

}
